---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wasm-pv
  namespace: gateway-system
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce # Rancher limitation?
  hostPath:
    path: /ej-data
    type: Directory

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wasm-pvc-1
  namespace: gateway-system
spec:
  volumeName: wasm-pv
  storageClassName: ""
  accessModes:
    - ReadWriteOnce # Rancher limitation?
  resources:
    requests:
      storage: 50Mi
